### ISSUE TITLE
当前代码中比你演示界面少了功能，能不能更新上来呀 谢谢

### ISSUE THREAD

**Issue by fxonei** [yongxiaodong/inspection_report#1]
代码中比你演示界面少了CDN授权信息、定时任务情况、开机加载项情况、服务器优化情况等等，作者能不能更新上来呀 谢谢，我自己修改了下详细报告中至增加了selinux优化情况，能力有限。。。

**Comment by yongxiaodong** [comment]
我添加了crontab收集和rc.local 收集功能，你可以试一下



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fxone"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 下午5:02
收件人:&nbsp;"yongxiaodong/inspection_report"<inspection_report@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yongxiaodong/inspection_report] 当前代码中比你演示界面少了功能，能不能更新上来呀 谢谢 (#1)





 
代码中比你演示界面少了CDN授权信息、定时任务情况、开机加载项情况、服务器优化情况等等，作者能不能更新上来呀 谢谢，我自己修改了下详细报告中至增加了selinux优化情况，能力有限。。。
